# mvn clean install -DskipTests=true && podman-compose build --no-cache && podman-compose up
# mvn clean install -DskipTests=true && docker-compose build --no-cache && docker-compose up
version: '3'
services:
  postgresql-ecommerce:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    networks:
      - my_network
  
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
