spring:
    application:
        name: Ecommerce
    banner.location: static/banner.txt
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 12345678
    jpa:
        properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
            show-sql: true

api.security.token.secret: ${JWT_SECRET:12345678}
